site_name: PlanktoScope
nav:
    - Setup:
        - Basic Install: easy_install.md
        - Expert Setup: expert_setup.md
    - Remote Access: remote_access.md
    - Usage:
        - Collection devices: collection_devices.md
    - Under the hood:
        - Software architecture: software_architecture.md
        - MQTT Messages: mqtt_messages.md
    - Contribute:
        - Edit this doc: edit_this_doc.md
        - Edit the code: edit_the_code.md
    - About:
        - License: license.md
theme:
  name: readthedocs
  collapse_navigation: false

markdown_extensions:
    - smarty
    - sane_lists
    - toc:
        permalink: true
